spring:
  application:
    name: pocket-market-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/pocket_market
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true
server:
  port: 8082
logging:
  level:
    com.pm : INFO
    
twilio:
  account:
    sid:  ajfladfla
  auth:
    token: tata
