spring:
  application:
    name: pocket-market-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/pocket_market
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    table: schema_history_pm_auth
    baseline-on-migrate: true
    baseline-version: 0.9
    placeholder-replacement: true
    placeholders:
      schemaName: public
server:
  port: 8084
    
twilio:
  account:
    sid:  ajfladfla
  auth:
    token: tata
    
cloud:
  aws:
    region:
      static: eu-west-1
    stack:
      auto: false
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://pm-db:5432/pocket_market
    username: postgres
    password: 1234